# Generated by Django 4.1.3 on 2022-12-11 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventTickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventID', models.CharField(max_length=30)),
                ('eventName', models.CharField(max_length=255)),
                ('eventDate', models.DateTimeField()),
                ('eventVenue', models.CharField(max_length=100)),
                ('eventLocation', models.CharField(max_length=100)),
                ('eventSection', models.CharField(max_length=30)),
                ('eventRow', models.CharField(max_length=30)),
                ('ticketPrice', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventInterests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interestedEvent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.eventtickets')),
            ],
        ),
    ]
